substitutions:
  hostid: 
  hostname: 
  comment: 
  node_platform: 
  node_board: 
  

packages:
  core: !include common/core.yaml # https://github.com/slimcdk/home-server/blob/master/services/esphome/common/core.yaml
  basic_sensors: !include common/basic_sensors.yaml # https://github.com/slimcdk/home-server/blob/master/services/esphome/common/basic_sensors.yaml
  

light:
  - platform: neopixelbus
    name: RGB RING
    variant: WS2812B
    type: GRB
    method: ESP8266_DMA
    num_leds: 12
    pin: GPIO16

  - platform: neopixelbus
    name: RGB SPOT
    variant: WS2812B
    type: GRB
    method: ESP8266_DMA
    num_leds: 40
    pin: GPIO17
